# Generated by Django 4.0.5 on 2022-07-16 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('question_marks', models.IntegerField(default=0)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
                ('is_delete', models.BooleanField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('cut_0ff_marks', models.PositiveIntegerField()),
                ('checker_review', models.TextField(blank=True, null=True)),
                ('examiner_review', models.TextField(blank=True, null=True)),
                ('is_checker_approved', models.BooleanField(default=False)),
                ('is_examinar_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checked_papers', to=settings.AUTH_USER_MODEL)),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='examined_papers', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='papers_app.question')),
                ('setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_papers', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers_app.subject'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_choice', models.CharField(choices=[('SETTER', 'Setter'), ('EXAMINAR', 'Examinar'), ('CHECKER', 'Checker')], max_length=10)),
                ('mobile_number', models.CharField(max_length=12)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingTestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_review', models.TextField(blank=True, null=True)),
                ('is_checker_approved', models.BooleanField(default=False)),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_check', to='papers_app.testpaper')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedTestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_review', models.TextField(blank=True, null=True)),
                ('is_examiner_approved', models.BooleanField(default=False)),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_approve', to='papers_app.testpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(blank=True, choices=[('TEXT', 'text_type'), ('IMAGE', 'image_type'), ('AUDIO', 'audio_type')], max_length=10, null=True)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers_app.question')),
            ],
        ),
    ]
