# Generated by Django 4.0.5 on 2022-07-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers_app.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
