# Generated by Django 4.0.5 on 2022-07-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_app', '0003_alter_profile_profile_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_choice',
            field=models.CharField(choices=[(0, 'Setter'), (2, 'Examinar'), (1, 'Checker')], max_length=10),
        ),
    ]
