# Generated by Django 4.0.5 on 2022-07-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers_app', '0005_answer_is_active_answer_is_delete_question_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpaper',
            old_name='cut_0ff_marks',
            new_name='cut_off_marks',
        ),
    ]
