# Generated by Django 4.0.5 on 2022-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_app', '0007_alter_testpaper_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='is_sent_for_cheeck',
            field=models.BooleanField(default=False),
        ),
    ]
