# Generated by Django 4.0.5 on 2022-09-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers_app', '0008_testpaper_is_sent_for_cheeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_choice',
            field=models.CharField(choices=[(0, 'Setter'), (2, 'Examinar'), (1, 'Checker')], default='0', max_length=10),
        ),
    ]
